export const API_ENDPOINTS = {
  SIGNUP: "/api/auth/signup",
  SIGNIN: "/api/auth/signin",
  VERIFY_EMAIL: "/api/auth/verify-email",
  RESEND_OTP: "/api/auth/resend-otp",
  FORGOT_PASSWORD: "/api/auth/forgot-password",
  RESET_PASSWORD: "/api/auth/reset-password",
  UPDATE_PROFILE: "/api/auth/profile",
  PRODUCTS: "/api/products",
  ADD_PRODUCT: "/api/products/add",
  CART: "/api/cart",
  ORDERS: "/api/orders",
  ADMIN_STATS: "/api/admin/stats",
  ADMIN_USERS: "/api/admin/users",
  ADMIN_PRODUCTS: "/api/admin/products",
  ADMIN_ORDERS: "/api/admin/orders",
  OFFERS: "/api/offers",
  ADMIN_OFFERS: "/api/offers/admin",
  WISHLIST: "/api/wishlist",
};
